//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace uds_test {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public string canSJW {
            get {
                return ((string)(this["canSJW"]));
            }
            set {
                this["canSJW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500K")]
        public string canFreq {
            get {
                return ((string)(this["canFreq"]));
            }
            set {
                this["canFreq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>False 000 8 00 00 00 00 00 00 00 00 100</string>
  <string>False 000 8 00 00 00 00 00 00 00 00 100</string>
  <string>False 000 8 00 00 00 00 00 00 00 00 100</string>
  <string>False 000 8 00 00 00 00 00 00 00 00 100</string>
  <string>False 000 8 00 00 00 00 00 00 00 00 100</string>
  <string>False 000 8 00 00 00 00 00 00 00 00 100</string>
  <string>False 000 8 00 00 00 00 00 00 00 00 100</string>
  <string>False 000 8 00 00 00 00 00 00 00 00 100</string>
</ArrayOfString>")]
        public string[] CtrlData {
            get {
                return ((string[])(this["CtrlData"]));
            }
            set {
                this["CtrlData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveFlag {
            get {
                return ((bool)(this["SaveFlag"]));
            }
            set {
                this["SaveFlag"] = value;
            }
        }
    }
}
